version: '3'
services:
  db:
    image: postgres:13.0
    ports:
    - "5432:5432"
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: meredith
      POSTGRES_PASSWORD: meredith
      POSTGRES_DB: meredith

volumes:
  db_data: {}