# https://docs.microsoft.com/azure/devops/pipelines/yaml-schema

trigger: none
pr:
  branches:
    include:
    - '*'

variables:
- name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
  value: true

pool:
  vmImage: 'windows-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore dotnet tools'
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'restore'

- task: DotNetCoreCLI@2
  displayName: 'Format'
  inputs:
    command: 'custom'
    custom: 'format'
    arguments: '--check --verbosity diagnostic'

- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: build
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: test
    projects: '*Tests/*.csproj'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: 'Check Swagger'
  inputs:
    command: 'custom'
    custom: 'swagger'
    arguments: 'tofile --output WhyNotEarth.Meredith.App\bin\Debug\netcoreapp3.1\swagger.json WhyNotEarth.Meredith.App\bin\Release\netcoreapp3.1\WhyNotEarth.Meredith.App.dll v0'