using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace WhyNotEarth.Meredith.Persistence.Migrations
{
    public partial class UpdateToPostgreSQL13 : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "DataProtectionKeys");

            migrationBuilder.DropColumn(
                name: "Id",
                table: "ShortUrls");

            migrationBuilder.AddColumn<int>(
                    name: "Id",
                    table: "ShortUrls",
                    nullable: false)
                .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            migrationBuilder.Sql(@"ALTER TABLE public.""Videos"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE public.""Videos"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE public.""Video_Id_seq"" RENAME TO ""Videos_Id_old_seq"";
                ALTER TABLE public.""Videos"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE public.""Videos"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('public.""Videos_Id_seq""', nextval('public.""Videos_Id_old_seq""'), false);
                DROP SEQUENCE public.""Videos_Id_old_seq"";

                ALTER TABLE public.""ShortMessages"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE public.""ShortMessages"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE public.""ShortMessages_Id_seq"" RENAME TO ""ShortMessages_Id_old_seq"";
                ALTER TABLE public.""ShortMessages"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE public.""ShortMessages"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('public.""ShortMessages_Id_seq""', nextval('public.""ShortMessages_Id_old_seq""'), false);
                DROP SEQUENCE public.""ShortMessages_Id_old_seq"";

                ALTER TABLE public.""Languages"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE public.""Languages"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE public.""Languages_Id_seq"" RENAME TO ""Languages_Id_old_seq"";
                ALTER TABLE public.""Languages"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE public.""Languages"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('public.""Languages_Id_seq""', nextval('public.""Languages_Id_old_seq""'), false);
                DROP SEQUENCE public.""Languages_Id_old_seq"";

                ALTER TABLE public.""Emails"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE public.""Emails"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE public.""MemoRecipients_Id_seq"" RENAME TO ""Emails_Id_old_seq"";
                ALTER TABLE public.""Emails"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE public.""Emails"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('public.""Emails_Id_seq""', nextval('public.""Emails_Id_old_seq""'), false);
                DROP SEQUENCE public.""Emails_Id_old_seq"";

                ALTER TABLE public.""EmailEvents"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE public.""EmailEvents"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE public.""EmailEvents_Id_seq"" RENAME TO ""EmailEvents_Id_old_seq"";
                ALTER TABLE public.""EmailEvents"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE public.""EmailEvents"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('public.""EmailEvents_Id_seq""', nextval('public.""EmailEvents_Id_old_seq""'), false);
                DROP SEQUENCE public.""EmailEvents_Id_old_seq"";

                ALTER TABLE ""ModuleVolkswagen"".""Recipients"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""ModuleVolkswagen"".""Recipients"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""ModuleVolkswagen"".""Recipients_Id_seq"" RENAME TO ""Recipients_Id_old_seq"";
                ALTER TABLE ""ModuleVolkswagen"".""Recipients"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""ModuleVolkswagen"".""Recipients"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""ModuleVolkswagen"".""Recipients_Id_seq""', nextval('""ModuleVolkswagen"".""Recipients_Id_old_seq""'), false);
                DROP SEQUENCE ""ModuleVolkswagen"".""Recipients_Id_old_seq"";

                ALTER TABLE ""ModuleVolkswagen"".""NewJumpStarts"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""ModuleVolkswagen"".""NewJumpStarts"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""ModuleVolkswagen"".""NewJumpStarts_Id_seq"" RENAME TO ""NewJumpStarts_Id_old_seq"";
                ALTER TABLE ""ModuleVolkswagen"".""NewJumpStarts"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""ModuleVolkswagen"".""NewJumpStarts"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""ModuleVolkswagen"".""NewJumpStarts_Id_seq""', nextval('""ModuleVolkswagen"".""NewJumpStarts_Id_old_seq""'), false);
                DROP SEQUENCE ""ModuleVolkswagen"".""NewJumpStarts_Id_old_seq"";

                ALTER TABLE ""ModuleVolkswagen"".""Memos"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""ModuleVolkswagen"".""Memos"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""ModuleVolkswagen"".""Memos_Id_seq"" RENAME TO ""Memos_Id_old_seq"";
                ALTER TABLE ""ModuleVolkswagen"".""Memos"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""ModuleVolkswagen"".""Memos"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""ModuleVolkswagen"".""Memos_Id_seq""', nextval('""ModuleVolkswagen"".""Memos_Id_old_seq""'), false);
                DROP SEQUENCE ""ModuleVolkswagen"".""Memos_Id_old_seq"";

                ALTER TABLE ""ModuleVolkswagen"".""JumpStarts"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""ModuleVolkswagen"".""JumpStarts"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""ModuleVolkswagen"".""JumpStarts_Id_seq"" RENAME TO ""JumpStarts_Id_old_seq"";
                ALTER TABLE ""ModuleVolkswagen"".""JumpStarts"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""ModuleVolkswagen"".""JumpStarts"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""ModuleVolkswagen"".""JumpStarts_Id_seq""', nextval('""ModuleVolkswagen"".""JumpStarts_Id_old_seq""'), false);
                DROP SEQUENCE ""ModuleVolkswagen"".""JumpStarts_Id_old_seq"";

                ALTER TABLE ""ModuleVolkswagen"".""Articles"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""ModuleVolkswagen"".""Articles"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""ModuleVolkswagen"".""Posts_Id_seq"" RENAME TO ""Articles_Id_old_seq"";
                ALTER TABLE ""ModuleVolkswagen"".""Articles"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""ModuleVolkswagen"".""Articles"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""ModuleVolkswagen"".""Articles_Id_seq""', nextval('""ModuleVolkswagen"".""Articles_Id_old_seq""'), false);
                DROP SEQUENCE ""ModuleVolkswagen"".""Articles_Id_old_seq"";

                ALTER TABLE ""ModuleShop"".""Variations"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""ModuleShop"".""Variations"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""ModuleShop"".""Variations_Id_seq"" RENAME TO ""Variations_Id_old_seq"";
                ALTER TABLE ""ModuleShop"".""Variations"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""ModuleShop"".""Variations"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""ModuleShop"".""Variations_Id_seq""', nextval('""ModuleShop"".""Variations_Id_old_seq""'), false);
                DROP SEQUENCE ""ModuleShop"".""Variations_Id_old_seq"";

                ALTER TABLE ""ModuleShop"".""Reservations"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""ModuleShop"".""Reservations"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""ModuleShop"".""Reservations_Id_seq"" RENAME TO ""Reservations_Id_old_seq"";
                ALTER TABLE ""ModuleShop"".""Reservations"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""ModuleShop"".""Reservations"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""ModuleShop"".""Reservations_Id_seq""', nextval('""ModuleShop"".""Reservations_Id_old_seq""'), false);
                DROP SEQUENCE ""ModuleShop"".""Reservations_Id_old_seq"";

                ALTER TABLE ""ModuleShop"".""Products"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""ModuleShop"".""Products"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""ModuleShop"".""Products_Id_seq"" RENAME TO ""Products_Id_old_seq"";
                ALTER TABLE ""ModuleShop"".""Products"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""ModuleShop"".""Products"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""ModuleShop"".""Products_Id_seq""', nextval('""ModuleShop"".""Products_Id_old_seq""'), false);
                DROP SEQUENCE ""ModuleShop"".""Products_Id_old_seq"";

                ALTER TABLE ""ModuleShop"".""ProductLocationInventories"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""ModuleShop"".""ProductLocationInventories"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""ModuleShop"".""ProductLocationInventories_Id_seq"" RENAME TO ""ProductLocationInventories_Id_old_seq"";
                ALTER TABLE ""ModuleShop"".""ProductLocationInventories"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""ModuleShop"".""ProductLocationInventories"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""ModuleShop"".""ProductLocationInventories_Id_seq""', nextval('""ModuleShop"".""ProductLocationInventories_Id_old_seq""'), false);
                DROP SEQUENCE ""ModuleShop"".""ProductLocationInventories_Id_old_seq"";

                ALTER TABLE ""ModuleShop"".""ProductAttributes"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""ModuleShop"".""ProductAttributes"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""ModuleShop"".""ProductAttributes_Id_seq"" RENAME TO ""ProductAttributes_Id_old_seq"";
                ALTER TABLE ""ModuleShop"".""ProductAttributes"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""ModuleShop"".""ProductAttributes"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""ModuleShop"".""ProductAttributes_Id_seq""', nextval('""ModuleShop"".""ProductAttributes_Id_old_seq""'), false);
                DROP SEQUENCE ""ModuleShop"".""ProductAttributes_Id_old_seq"";

                ALTER TABLE ""ModuleShop"".""Prices"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""ModuleShop"".""Prices"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""ModuleShop"".""Prices_Id_seq"" RENAME TO ""Prices_Id_old_seq"";
                ALTER TABLE ""ModuleShop"".""Prices"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""ModuleShop"".""Prices"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""ModuleShop"".""Prices_Id_seq""', nextval('""ModuleShop"".""Prices_Id_old_seq""'), false);
                DROP SEQUENCE ""ModuleShop"".""Prices_Id_old_seq"";

                ALTER TABLE ""ModuleShop"".""Payments"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""ModuleShop"".""Payments"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""ModuleShop"".""Payments_Id_seq"" RENAME TO ""Payments_Id_old_seq"";
                ALTER TABLE ""ModuleShop"".""Payments"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""ModuleShop"".""Payments"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""ModuleShop"".""Payments_Id_seq""', nextval('""ModuleShop"".""Payments_Id_old_seq""'), false);
                DROP SEQUENCE ""ModuleShop"".""Payments_Id_old_seq"";

                ALTER TABLE ""ModuleShop"".""Orders"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""ModuleShop"".""Orders"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""ModuleShop"".""Orders_Id_seq"" RENAME TO ""Orders_Id_old_seq"";
                ALTER TABLE ""ModuleShop"".""Orders"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""ModuleShop"".""Orders"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""ModuleShop"".""Orders_Id_seq""', nextval('""ModuleShop"".""Orders_Id_old_seq""'), false);
                DROP SEQUENCE ""ModuleShop"".""Orders_Id_old_seq"";

                ALTER TABLE ""ModuleShop"".""OrderLines"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""ModuleShop"".""OrderLines"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""ModuleShop"".""OrderLines_Id_seq"" RENAME TO ""OrderLines_Id_old_seq"";
                ALTER TABLE ""ModuleShop"".""OrderLines"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""ModuleShop"".""OrderLines"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""ModuleShop"".""OrderLines_Id_seq""', nextval('""ModuleShop"".""OrderLines_Id_old_seq""'), false);
                DROP SEQUENCE ""ModuleShop"".""OrderLines_Id_old_seq"";

                ALTER TABLE ""ModuleShop"".""Locations"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""ModuleShop"".""Locations"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""ModuleShop"".""Locations_Id_seq"" RENAME TO ""Locations_Id_old_seq"";
                ALTER TABLE ""ModuleShop"".""Locations"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""ModuleShop"".""Locations"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""ModuleShop"".""Locations_Id_seq""', nextval('""ModuleShop"".""Locations_Id_old_seq""'), false);
                DROP SEQUENCE ""ModuleShop"".""Locations_Id_old_seq"";

                ALTER TABLE ""ModuleShop"".""BusinessHours"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""ModuleShop"".""BusinessHours"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""ModuleShop"".""BusinessHours_Id_seq"" RENAME TO ""BusinessHours_Id_old_seq"";
                ALTER TABLE ""ModuleShop"".""BusinessHours"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""ModuleShop"".""BusinessHours"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""ModuleShop"".""BusinessHours_Id_seq""', nextval('""ModuleShop"".""BusinessHours_Id_old_seq""'), false);
                DROP SEQUENCE ""ModuleShop"".""BusinessHours_Id_old_seq"";

                ALTER TABLE ""ModuleShop"".""Addresses"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""ModuleShop"".""Addresses"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""ModuleShop"".""Addresses_Id_seq"" RENAME TO ""Addresses_Id_old_seq"";
                ALTER TABLE ""ModuleShop"".""Addresses"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""ModuleShop"".""Addresses"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""ModuleShop"".""Addresses_Id_seq""', nextval('""ModuleShop"".""Addresses_Id_old_seq""'), false);
                DROP SEQUENCE ""ModuleShop"".""Addresses_Id_old_seq"";

                ALTER TABLE ""ModuleHotel"".""SpaceTranslations"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""ModuleHotel"".""SpaceTranslations"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""ModuleHotel"".""SpaceTranslations_Id_seq"" RENAME TO ""SpaceTranslations_Id_old_seq"";
                ALTER TABLE ""ModuleHotel"".""SpaceTranslations"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""ModuleHotel"".""SpaceTranslations"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""ModuleHotel"".""SpaceTranslations_Id_seq""', nextval('""ModuleHotel"".""SpaceTranslations_Id_old_seq""'), false);
                DROP SEQUENCE ""ModuleHotel"".""SpaceTranslations_Id_old_seq"";

                ALTER TABLE ""ModuleHotel"".""Spaces"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""ModuleHotel"".""Spaces"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""ModuleHotel"".""Spaces_Id_seq"" RENAME TO ""Spaces_Id_old_seq"";
                ALTER TABLE ""ModuleHotel"".""Spaces"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""ModuleHotel"".""Spaces"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""ModuleHotel"".""Spaces_Id_seq""', nextval('""ModuleHotel"".""Spaces_Id_old_seq""'), false);
                DROP SEQUENCE ""ModuleHotel"".""Spaces_Id_old_seq"";

                ALTER TABLE ""ModuleHotel"".""RuleTranslations"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""ModuleHotel"".""RuleTranslations"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""ModuleHotel"".""RuleTranslations_Id_seq"" RENAME TO ""RuleTranslations_Id_old_seq"";
                ALTER TABLE ""ModuleHotel"".""RuleTranslations"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""ModuleHotel"".""RuleTranslations"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""ModuleHotel"".""RuleTranslations_Id_seq""', nextval('""ModuleHotel"".""RuleTranslations_Id_old_seq""'), false);
                DROP SEQUENCE ""ModuleHotel"".""RuleTranslations_Id_old_seq"";

                ALTER TABLE ""ModuleHotel"".""Rules"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""ModuleHotel"".""Rules"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""ModuleHotel"".""Rules_Id_seq"" RENAME TO ""Rules_Id_old_seq"";
                ALTER TABLE ""ModuleHotel"".""Rules"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""ModuleHotel"".""Rules"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""ModuleHotel"".""Rules_Id_seq""', nextval('""ModuleHotel"".""Rules_Id_old_seq""'), false);
                DROP SEQUENCE ""ModuleHotel"".""Rules_Id_old_seq"";

                ALTER TABLE ""ModuleHotel"".""RoomTypes"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""ModuleHotel"".""RoomTypes"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""ModuleHotel"".""RoomTypes_Id_seq"" RENAME TO ""RoomTypes_Id_old_seq"";
                ALTER TABLE ""ModuleHotel"".""RoomTypes"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""ModuleHotel"".""RoomTypes"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""ModuleHotel"".""RoomTypes_Id_seq""', nextval('""ModuleHotel"".""RoomTypes_Id_old_seq""'), false);
                DROP SEQUENCE ""ModuleHotel"".""RoomTypes_Id_old_seq"";

                ALTER TABLE ""ModuleHotel"".""Rooms"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""ModuleHotel"".""Rooms"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""ModuleHotel"".""Rooms_Id_seq"" RENAME TO ""Rooms_Id_old_seq"";
                ALTER TABLE ""ModuleHotel"".""Rooms"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""ModuleHotel"".""Rooms"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""ModuleHotel"".""Rooms_Id_seq""', nextval('""ModuleHotel"".""Rooms_Id_old_seq""'), false);
                DROP SEQUENCE ""ModuleHotel"".""Rooms_Id_old_seq"";

                ALTER TABLE ""ModuleHotel"".""HotelTranslations"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""ModuleHotel"".""HotelTranslations"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""ModuleHotel"".""HotelTranslations_Id_seq"" RENAME TO ""HotelTranslations_Id_old_seq"";
                ALTER TABLE ""ModuleHotel"".""HotelTranslations"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""ModuleHotel"".""HotelTranslations"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""ModuleHotel"".""HotelTranslations_Id_seq""', nextval('""ModuleHotel"".""HotelTranslations_Id_old_seq""'), false);
                DROP SEQUENCE ""ModuleHotel"".""HotelTranslations_Id_old_seq"";

                ALTER TABLE ""ModuleHotel"".""Hotels"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""ModuleHotel"".""Hotels"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""ModuleHotel"".""Hotels_Id_seq"" RENAME TO ""Hotels_Id_old_seq"";
                ALTER TABLE ""ModuleHotel"".""Hotels"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""ModuleHotel"".""Hotels"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""ModuleHotel"".""Hotels_Id_seq""', nextval('""ModuleHotel"".""Hotels_Id_old_seq""'), false);
                DROP SEQUENCE ""ModuleHotel"".""Hotels_Id_old_seq"";

                ALTER TABLE ""ModuleHotel"".""Beds"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""ModuleHotel"".""Beds"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""ModuleHotel"".""Beds_Id_seq"" RENAME TO ""Beds_Id_old_seq"";
                ALTER TABLE ""ModuleHotel"".""Beds"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""ModuleHotel"".""Beds"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""ModuleHotel"".""Beds_Id_seq""', nextval('""ModuleHotel"".""Beds_Id_old_seq""'), false);
                DROP SEQUENCE ""ModuleHotel"".""Beds_Id_old_seq"";

                ALTER TABLE ""ModuleHotel"".""AmenityTranslations"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""ModuleHotel"".""AmenityTranslations"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""ModuleHotel"".""AmenityTranslations_Id_seq"" RENAME TO ""AmenityTranslations_Id_old_seq"";
                ALTER TABLE ""ModuleHotel"".""AmenityTranslations"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""ModuleHotel"".""AmenityTranslations"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""ModuleHotel"".""AmenityTranslations_Id_seq""', nextval('""ModuleHotel"".""AmenityTranslations_Id_old_seq""'), false);
                DROP SEQUENCE ""ModuleHotel"".""AmenityTranslations_Id_old_seq"";

                ALTER TABLE ""ModuleHotel"".""Amenities"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""ModuleHotel"".""Amenities"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""ModuleHotel"".""Amenities_Id_seq"" RENAME TO ""Amenities_Id_old_seq"";
                ALTER TABLE ""ModuleHotel"".""Amenities"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""ModuleHotel"".""Amenities"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""ModuleHotel"".""Amenities_Id_seq""', nextval('""ModuleHotel"".""Amenities_Id_old_seq""'), false);
                DROP SEQUENCE ""ModuleHotel"".""Amenities_Id_old_seq"";

                ALTER TABLE ""ModuleBrowTricks"".""FormTemplates"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""ModuleBrowTricks"".""FormTemplates"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""ModuleBrowTricks"".""FormTemplates_Id_seq"" RENAME TO ""FormTemplates_Id_old_seq"";
                ALTER TABLE ""ModuleBrowTricks"".""FormTemplates"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""ModuleBrowTricks"".""FormTemplates"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""ModuleBrowTricks"".""FormTemplates_Id_seq""', nextval('""ModuleBrowTricks"".""FormTemplates_Id_old_seq""'), false);
                DROP SEQUENCE ""ModuleBrowTricks"".""FormTemplates_Id_old_seq"";

                ALTER TABLE ""ModuleBrowTricks"".""FormSignatures"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""ModuleBrowTricks"".""FormSignatures"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""ModuleBrowTricks"".""FormSignatures_Id_seq"" RENAME TO ""FormSignatures_Id_old_seq"";
                ALTER TABLE ""ModuleBrowTricks"".""FormSignatures"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""ModuleBrowTricks"".""FormSignatures"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""ModuleBrowTricks"".""FormSignatures_Id_seq""', nextval('""ModuleBrowTricks"".""FormSignatures_Id_old_seq""'), false);
                DROP SEQUENCE ""ModuleBrowTricks"".""FormSignatures_Id_old_seq"";

                ALTER TABLE ""ModuleBrowTricks"".""FormItems"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""ModuleBrowTricks"".""FormItems"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""ModuleBrowTricks"".""FormItems_Id_seq"" RENAME TO ""FormItems_Id_old_seq"";
                ALTER TABLE ""ModuleBrowTricks"".""FormItems"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""ModuleBrowTricks"".""FormItems"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""ModuleBrowTricks"".""FormItems_Id_seq""', nextval('""ModuleBrowTricks"".""FormItems_Id_old_seq""'), false);
                DROP SEQUENCE ""ModuleBrowTricks"".""FormItems_Id_old_seq"";

                ALTER TABLE ""ModuleBrowTricks"".""FormAnswers"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""ModuleBrowTricks"".""FormAnswers"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""ModuleBrowTricks"".""FormAnswers_Id_seq"" RENAME TO ""FormAnswers_Id_old_seq"";
                ALTER TABLE ""ModuleBrowTricks"".""FormAnswers"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""ModuleBrowTricks"".""FormAnswers"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""ModuleBrowTricks"".""FormAnswers_Id_seq""', nextval('""ModuleBrowTricks"".""FormAnswers_Id_old_seq""'), false);
                DROP SEQUENCE ""ModuleBrowTricks"".""FormAnswers_Id_old_seq"";

                ALTER TABLE ""ModuleBrowTricks"".""Clients"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""ModuleBrowTricks"".""Clients"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""ModuleBrowTricks"".""Clients_Id_seq"" RENAME TO ""Clients_Id_old_seq"";
                ALTER TABLE ""ModuleBrowTricks"".""Clients"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""ModuleBrowTricks"".""Clients"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""ModuleBrowTricks"".""Clients_Id_seq""', nextval('""ModuleBrowTricks"".""Clients_Id_old_seq""'), false);
                DROP SEQUENCE ""ModuleBrowTricks"".""Clients_Id_old_seq"";

                ALTER TABLE ""ModuleBrowTricks"".""ClientNotes"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""ModuleBrowTricks"".""ClientNotes"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""ModuleBrowTricks"".""ClientNotes_Id_seq"" RENAME TO ""ClientNotes_Id_old_seq"";
                ALTER TABLE ""ModuleBrowTricks"".""ClientNotes"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""ModuleBrowTricks"".""ClientNotes"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""ModuleBrowTricks"".""ClientNotes_Id_seq""', nextval('""ModuleBrowTricks"".""ClientNotes_Id_old_seq""'), false);
                DROP SEQUENCE ""ModuleBrowTricks"".""ClientNotes_Id_old_seq"";

                ALTER TABLE ""Users"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""Users"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""Users_Id_seq"" RENAME TO ""Users_Id_old_seq"";
                ALTER TABLE ""Users"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""Users"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""Users_Id_seq""', nextval('""Users_Id_old_seq""'), false);
                DROP SEQUENCE ""Users_Id_old_seq"";

                ALTER TABLE ""TwilioAccounts"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""TwilioAccounts"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""TwilioAccounts_Id_seq"" RENAME TO ""TwilioAccounts_Id_old_seq"";
                ALTER TABLE ""TwilioAccounts"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""TwilioAccounts"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""TwilioAccounts_Id_seq""', nextval('""TwilioAccounts_Id_old_seq""'), false);
                DROP SEQUENCE ""TwilioAccounts_Id_old_seq"";

                ALTER TABLE ""Tenants"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""Tenants"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""Tenants_Id_seq"" RENAME TO ""Tenants_Id_old_seq"";
                ALTER TABLE ""Tenants"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""Tenants"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""Tenants_Id_seq""', nextval('""Tenants_Id_old_seq""'), false);
                DROP SEQUENCE ""Tenants_Id_old_seq"";

                ALTER TABLE ""StripeAccounts"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""StripeAccounts"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""StripeAccounts_Id_seq"" RENAME TO ""StripeAccounts_Id_old_seq"";
                ALTER TABLE ""StripeAccounts"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""StripeAccounts"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""StripeAccounts_Id_seq""', nextval('""StripeAccounts_Id_old_seq""'), false);
                DROP SEQUENCE ""StripeAccounts_Id_old_seq"";

                ALTER TABLE ""Settings"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""Settings"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""Settings_Id_seq"" RENAME TO ""Settings_Id_old_seq"";
                ALTER TABLE ""Settings"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""Settings"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""Settings_Id_seq""', nextval('""Settings_Id_old_seq""'), false);
                DROP SEQUENCE ""Settings_Id_old_seq"";

                ALTER TABLE ""SendGridAccounts"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""SendGridAccounts"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""SendGridAccounts_Id_seq"" RENAME TO ""SendGridAccounts_Id_old_seq"";
                ALTER TABLE ""SendGridAccounts"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""SendGridAccounts"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""SendGridAccounts_Id_seq""', nextval('""SendGridAccounts_Id_old_seq""'), false);
                DROP SEQUENCE ""SendGridAccounts_Id_old_seq"";

                ALTER TABLE ""Roles"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""Roles"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""Roles_Id_seq"" RENAME TO ""Roles_Id_old_seq"";
                ALTER TABLE ""Roles"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""Roles"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""Roles_Id_seq""', nextval('""Roles_Id_old_seq""'), false);
                DROP SEQUENCE ""Roles_Id_old_seq"";

                ALTER TABLE ""Products"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""Products"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""Products_Id_seq"" RENAME TO ""Products_Id_old_seq"";
                ALTER TABLE ""Products"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""Products"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""Products_Id_seq""', nextval('""Products_Id_old_seq""'), false);
                DROP SEQUENCE ""Products_Id_old_seq"";

                ALTER TABLE ""PageTranslation"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""PageTranslation"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""PageTranslation_Id_seq"" RENAME TO ""PageTranslation_Id_old_seq"";
                ALTER TABLE ""PageTranslation"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""PageTranslation"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""PageTranslation_Id_seq""', nextval('""PageTranslation_Id_old_seq""'), false);
                DROP SEQUENCE ""PageTranslation_Id_old_seq"";

                ALTER TABLE ""Pages"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""Pages"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""Pages_Id_seq"" RENAME TO ""Pages_Id_old_seq"";
                ALTER TABLE ""Pages"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""Pages"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""Pages_Id_seq""', nextval('""Pages_Id_old_seq""'), false);
                DROP SEQUENCE ""Pages_Id_old_seq"";

                ALTER TABLE ""Keywords"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""Keywords"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""Keywords_Id_seq"" RENAME TO ""Keywords_Id_old_seq"";
                ALTER TABLE ""Keywords"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""Keywords"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""Keywords_Id_seq""', nextval('""Keywords_Id_old_seq""'), false);
                DROP SEQUENCE ""Keywords_Id_old_seq"";

                ALTER TABLE ""Images"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""Images"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""Images_Id_seq"" RENAME TO ""Images_Id_old_seq"";
                ALTER TABLE ""Images"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""Images"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""Images_Id_seq""', nextval('""Images_Id_old_seq""'), false);
                DROP SEQUENCE ""Images_Id_old_seq"";

                ALTER TABLE ""Companies"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""Companies"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""Companies_Id_seq"" RENAME TO ""Companies_Id_old_seq"";
                ALTER TABLE ""Companies"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""Companies"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""Companies_Id_seq""', nextval('""Companies_Id_old_seq""'), false);
                DROP SEQUENCE ""Companies_Id_old_seq"";

                ALTER TABLE ""Categories"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""Categories"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""Categories_Id_seq"" RENAME TO ""Categories_Id_old_seq"";
                ALTER TABLE ""Categories"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""Categories"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""Categories_Id_seq""', nextval('""Categories_Id_old_seq""'), false);
                DROP SEQUENCE ""Categories_Id_old_seq"";

                ALTER TABLE ""Cards"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""Cards"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""Cards_Id_seq"" RENAME TO ""Cards_Id_old_seq"";
                ALTER TABLE ""Cards"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""Cards"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""Cards_Id_seq""', nextval('""Cards_Id_old_seq""'), false);
                DROP SEQUENCE ""Cards_Id_old_seq"";

                ALTER TABLE ""AspNetUserClaims"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""AspNetUserClaims"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""AspNetUserClaims_Id_seq"" RENAME TO ""AspNetUserClaims_Id_old_seq"";
                ALTER TABLE ""AspNetUserClaims"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""AspNetUserClaims"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""AspNetUserClaims_Id_seq""', nextval('""AspNetUserClaims_Id_old_seq""'), false);
                DROP SEQUENCE ""AspNetUserClaims_Id_old_seq"";

                ALTER TABLE ""AspNetRoleClaims"" ALTER COLUMN ""Id"" TYPE integer;
                ALTER TABLE ""AspNetRoleClaims"" ALTER COLUMN ""Id"" SET NOT NULL;
                ALTER SEQUENCE ""AspNetRoleClaims_Id_seq"" RENAME TO ""AspNetRoleClaims_Id_old_seq"";
                ALTER TABLE ""AspNetRoleClaims"" ALTER COLUMN ""Id"" DROP DEFAULT;
                ALTER TABLE ""AspNetRoleClaims"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT * FROM setval('""AspNetRoleClaims_Id_seq""', nextval('""AspNetRoleClaims_Id_old_seq""'), false);
                DROP SEQUENCE ""AspNetRoleClaims_Id_old_seq"";");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
        }
    }
}
